name: learn-github-actions
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: yarn install
      - name: build project
        run: CI=false yarn build
      - name: unit test
        run: yarn run test
      - name: e2e test
        run: yarn run test:e2e
      - name: lint code
        run: yarn run lint
      - name: heroku add
        run: yarn run heroku_push
      - name: heroku commit
        run: yarn run heroku_push
      - name: heroku push
        run: yarn run heroku_push
