name: learn-github-actions
on: [ push ]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-varsion:[16.x]
    steps:
      - uses: actions/checkout@v3
                - name: Staring Node.js ${{ matrix.node-varsion }}
                uses: actions/setup-node@v3
                with:
                  node-version: ${{ matrix.node-version }}
                  - name: install modules
                    run: yarn install
                  - name: build project
                    run: yarn run build
                  - name: unit test
                    run: yarn run test:unit
                  - name: e2e test
                    run: yarn run test:e2e
                  - name: lint code
                    run: yarn run lint

